mongo:
  host: 127.0.0.1
  port: 27017
  database: Coffee
  timeout: 3000
  auth:
    enabled: false
    username: ""
    password: ""
    authDatabase: ""

redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  channel: coffee-comms
  auth:
    enabled: false
    password: ""